<?php

namespace app\models;
use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "products".
 *
 * @property int $id
 * @property string $title
 * @property string $body
 * @property int $price
 * @property int $image_id
 * @property int $status
 * @property int $created_at
 * @property int $updated_at
 * @property int $deleted_at
 *
 * @property ProductsCategory[] $productsCategories
 * @property Category[] $categories
 */
class Products extends \yii\db\ActiveRecord
{

    public $selected_categories;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'products';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['body'], 'string'],
            [['selected_categories'], 'safe'],
            [['price', 'image_id', 'status', 'created_at', 'updated_at', 'deleted_at'], 'integer'],
            [['title'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'body' => 'Body',
            'price' => 'Price',
            'image_id' => 'Image ID',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProductsCategories()
    {
        return $this->hasMany(ProductsCategory::className(), ['products_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasMany(Category::className(), ['id' => 'category_id'])->viaTable('products_category', ['products_id' => 'id']);
    }

    public function getAllCategoriesAsArray()
    {
        $categories = \app\models\Category::find()->all();
        $dropdownData = ArrayHelper::map($categories, 'id', 'title');
        return $dropdownData;
    }

    public function afterSave($insert, $changedAttributes)
    {
        if ($insert == false) {
            $this->unlinkAll('category', true);
        }
        foreach ($this->selected_categories as $category_id) {
            $temp = Category::findOne($category_id);
            $this->link('category', $temp);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
